version: '3.8'
services:
  api:
    container_name: 'mixtrack-restful-api'
    build: .
    ports:
      - 3000:3000
    links:
      - database
    env_file: '.env'
  database:
    container_name: 'mixtrack-database'
    image: mongo
    ports:
      - 27017:27017
  cache:
    container_name: 'mixtrack-cache'
    image: redis
    ports:
      - 6379:6379
    command: 'redis-server'