version: 2.1

jobs:
  run_tests:
    docker:
      - image: cicleci/node:18.16
    steps:
      - checkout
      - run:
        name: 'install npm packages'
        command: |
          npm install
      - run:
        name: 'run linting'
        command: |
          npm run lint

workflows:
  build_tests:
    jobs:
      - run_tests